var express=require("express"),http=require("http"),fs=require("fs"),path=require("path"),mongoose=require("mongoose"),io=require("socket.io"),ObjId=require("mongodb").ObjectID,mongoURI=process.env.MONGOLAB_URI||"mongodb://127.0.0.1/todos",options={server:{poolSize:5,socketOptions:{keepAlive:1}}},db=mongoose.connect(mongoURI,options),Schema=mongoose.Schema,ObjectID=Schema.ObjectId,EM=require("./app/server/modules/email-dispatcher"),routes=require("./auth_routes"),ExternalUserHandler=require("./handlers/ExternalUserHandler"),
AuthHandler=require("./handlers/AuthHandler"),passport=require("passport"),google_strategy=require("passport-google-oauth").OAuth2Strategy,windowslive_Strategy=require("passport-windowslive"),facebook_strategy=require("passport-facebook"),linkedIn_strategy=require("passport-linkedin").Strategy,YahooStrategy=require("passport-yahoo").Strategy,twitter_strategy=require("passport-twitter"),app=module.exports=express();app.mongoose=require("mongoose");var models={};models.Registration=require("./models/registration.js")(app.mongoose).model;
models.BlogPost=require("./models/blogpost.js")(app.mongoose).model;models.EssayTopic=require("./models/essayTopic.js")(app.mongoose).model;models.Feedback=require("./models/feedback.js")(app.mongoose).model;models.SessionData=require("./models/sessionData.js")(app.mongoose).model;models.LoginRecord=require("./models/loginRecord.js")(app.mongoose).model;models.ExternalUser=require("./models/ExternalUser.js")(app.mongoose).model;
app.configure(function(){app.set("port",process.env.PORT||80);app.set("views",__dirname+"/app/server/views");app.set("view engine","jade");process.env.NODE_TLS_REJECT_UNAUTHORIZED="0";app.locals.pretty=!0;app.use(express.favicon(__dirname+"/public/favicon.ico"));app.set("view options",{layout:!1});app.use(express.json());app.use(express.urlencoded());app.use(express.cookieParser());app.use(express.session({secret:"super-duper-secret-secret"}));app.use(express.methodOverride());app.use(express.static(path.join(__dirname,
"public")));app.use(require("stylus").middleware({src:__dirname+"/app/public"}));app.use(express.static(__dirname+"/app/public"));app.use(passport.initialize());app.set("client-url","http://www.cliquelearn.org");app.set("client-google-signin","/google?action=signin");app.disable("x-powered-by");app.use(app.router)});
var allowCrossDomain=function(b,d,a){d.header("Access-Control-Allow-Origin","*");d.header("Access-Control-Allow-Methods","GET,PUT,POST,DELETE");d.header("Access-Control-Allow-Headers","Content-Type, Authorization");"OPTIONS"==b.method?d.send(200):a()};passport.serializeUser(function(b,d){d(null,b)});passport.deserializeUser(function(b,d){d(null,b)});
passport.use(new google_strategy({clientID:"135981056725-9h7pv94fq7l1b4tsh5hh5lor6i02qofl.apps.googleusercontent.com",clientSecret:"z7dCXbnbzXzM8n8Y-UcbJArH",callbackURL:"http://www.cliquelearn.org/auth/google/callback"},function(b,d,a,c){models.ExternalUser.update({email:a._json.emails[0].value},{last_name:"undefined"===typeof a._json.name.familyName?"":a._json.name.familyName,first_name:"undefined"===typeof a._json.name.givenName?"":a._json.name.givenName,email:"undefined"===typeof a._json.emails[0].value?
"":a._json.emails[0].value,token:b},{upsert:!0},function(b,d){b&&console.log(b);process.nextTick(function(){return c(null,a)})})}));
passport.use(new windowslive_Strategy({clientID:"0000000040178602",clientSecret:"xWCJqfZYPT76nQ7U0drWkP3LcMv6WEua",callbackURL:"http://www.cliquelearn.org/auth/windowslive/callback"},function(b,d,a,c){models.ExternalUser.update({email:a._json.emails.preferred},{last_name:"undefined"===typeof a._json.last_name?"":a._json.last_name,first_name:"undefined"===typeof a._json.first_name?"":a._json.first_name,email:"undefined"===typeof a._json.emails.preferred?"":a._json.emails.preferred,token:b},{upsert:!0},
function(b,d){b&&console.log(b);process.nextTick(function(){return c(null,a)})})}));
passport.use(new facebook_strategy({clientID:"101528843551743",clientSecret:"5acdd4bf1c9c4fa20d1fee7dd6062f88",callbackURL:"http://www.cliquelearn.org/auth/facebook/callback",enableProof:!1},function(b,d,a,c){models.ExternalUser.update({email:a._json.email},{last_name:"undefined"===typeof a._json.last_name?"":a._json.last_name,first_name:"undefined"===typeof a._json.first_name?"":a._json.first_name,email:"undefined"===typeof a._json.email?"":a._json.email,token:b},{upsert:!0},function(b,d){b&&console.log(b);
process.nextTick(function(){return c(null,a)})})}));passport.use(new linkedIn_strategy({consumerKey:"75o4ldp4squ3kh",consumerSecret:"SUNfIaKnQJe452BD",callbackURL:"http://www.cliquelearn.org/auth/linkedIn/callback"},function(b,d,a,c){process.nextTick(function(){return c(null,a)})}));
passport.use(new YahooStrategy({clientId:"dj0yJmk9azRhRXhnTUtZVW1ZJmQ9WVdrOU0xZHVlSHBQTldNbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD02Zg--",clientSecret:"ed9005f68736cf3ede6ca8c0f66b078b87ea9794",returnURL:"http://cliqueserv.org/auth/yahoo/return",realm:"http://cliqueserv.org/"},function(b,d,a){models.ExternalUser.update({email:d.emails[0].value},{last_name:"",first_name:"undefined"===typeof d.displayName?"":d.displayName,email:"undefined"===typeof d.emails[0].value?"":d.emails[0].value,token:b},{upsert:!0},
function(c,f){c&&console.log(c);process.nextTick(function(){d.identifier=b;return a(null,d)})})}));
passport.use(new twitter_strategy({consumerKey:"K0u1jqk9wB8XvhZLysyc0AjXJ",consumerSecret:"s1o3yHlytlpwfyCgwMAEvb14V5isH2TpCxRKjMfxCRwjZ7lORB",callbackURL:"http://www.cliquelearn.org/auth/twitter/callback"},function(b,d,a,c){models.ExternalUser.update({email:a.username+"@twitter.com"},{last_name:"",first_name:"undefined"===typeof a.displayName?"":a.displayName,email:"undefined"===typeof a.username?"":a.username+"@twitter.com",token:b},{upsert:!0},function(b,d){b&&console.log(b);process.nextTick(function(){return c(null,
a)})})}));var handlers={ExternalUser:new ExternalUserHandler,auth:new AuthHandler};routes.setup(app,handlers);require("./app/server/router")(app,models);var server=http.createServer(app).listen(app.get("port"),function(){console.log("Express server listening on port "+app.get("port"))}),sio=io.listen(server),users=0,userNames=function(){var b={};return{claim:function(d){return!d||b[d]?!1:b[d]=!0},free:function(d){b[d]&&delete b[d]},get:function(){var d=[];for(user in b)d.push(user);return d}}}();
sio.sockets.on("connection",function(b){users++;b.emit("count",{count:users});b.broadcast.emit("count",{count:users});var d=[];b.emit("newUserList",{userList:d});b.on("addUser",function(c){var a=c.name,e=c.testname;"undefined"===typeof a?console.log("User logged off!"):(b.username=a,console.log(a+" has joined"),d.push(a),b.emit("updateUserList",{user:a,connectionType:"add"}),fs.stat(__dirname+"/lib/"+e+".json",function(c,a){c||fs.readFile(__dirname+"/lib/"+e+".json","Utf-8",function(c,a){c?console.log(c):
b.emit("sendQuestions",JSON.parse(a))})}))});b.on("destroysession",function(b){models.SessionData.remove({sessionId:b},function(b){b&&console.log(b)})});b.on("viewscores",function(c){models.ProgressReport.find({$and:[{userId:c},{score:{$exists:!0}}]},function(c,a){b.emit("allscores",a)})});b.on("selectedTopic",function(c){c=fs.readFileSync(__dirname+"/app/server/views/courses/"+c.course+"/"+c.subsection+"/"+c.topic+".html","ascii");b.emit("topicfound",c)});var a="";b.on("init",function(c){a=c;userNames.claim(c);
b.emit("init",{name:c,users:userNames.get()});b.broadcast.emit("user:join",{name:c})});b.on("loadextusers",function(){models.ExternalUser.find({},function(c,a){c||b.emit("extusersfound",a)})});b.on("deleteextuser",function(b){models.ExternalUser.remove({email:b},function(b){b&&console.log(b)})});b.on("getessaytopic",function(c){models.EssayTopic.count({},function(c,a){if(!c){var d=1+Math.floor(Math.random()*a);models.EssayTopic.find({topicId:d},function(c,a){c?console.log(c):0==a.length?b.emit("topicnotfound",
"Error: Can't generate topics"):b.emit("topicfound",a[0].essayTopic)})}})});b.on("loadcourses",function(c){models.Course.findOne({studygroup:c.studygroup},function(a,d){d&&(1==c.searchItem?b.emit("coursefound",d):2==c.searchItem?b.emit("referencefound",d):3==c.searchItem&&b.emit("linkfound",d))})});b.on("addcourse",function(c){models.Course.update({studyGroup:c.studyGroup},{$addToSet:{links:{courseCaption:c.courseCaption,courseHyperLink:c.courseHyperLink,courseType:c.courseType}}},{upsert:!0},function(a,
d){a?console.log(a):models.Course.findOne({studygroup:c.studygroup},function(c,a){a&&b.emit("coursechanged",a)})})});b.on("addreference",function(c){models.Course.update({studyGroup:c.studyGroup},{$addToSet:{referenceMaterials:{courseCaption:c.courseCaption,courseHyperLink:c.courseHyperLink,courseType:c.courseType}}},{upsert:!0},function(a,d){a?console.log(a):models.Course.findOne({studygroup:c.studygroup},function(c,a){a&&b.emit("referencechanged",a)})})});b.on("addlink",function(c){models.Course.update({studyGroup:c.studyGroup},
{$addToSet:{referenceLinks:{courseCaption:c.courseCaption,courseHyperLink:c.courseHyperLink,courseType:c.courseType}}},{upsert:!0},function(a,d){a?console.log(a):models.Course.findOne({studygroup:c.studygroup},function(c,a){a&&b.emit("linkchanged",a)})})});b.on("deleteCourseTopic",function(c){models.Course.update({studyGroup:c.studyGroup},{$pull:{links:{courseCaption:c.courseCaption}}},{upsert:!1},function(a,d){a?console.log(a):models.Course.findOne({studygroup:c.studygroup},function(c,a){a&&b.emit("coursechanged",
a)})})});b.on("deleteReferenceTopic",function(c){models.Course.update({studyGroup:c.studyGroup},{$pull:{referenceMaterials:{courseCaption:c.courseCaption}}},{upsert:!1},function(a,d){a?console.log(a):models.Course.findOne({studygroup:c.studygroup},function(a,c){c&&b.emit("referencechanged",c)})})});b.on("deleteLinkTopic",function(c){models.Course.update({studyGroup:c.studyGroup},{$pull:{referenceLinks:{courseCaption:c.courseCaption}}},{upsert:!1},function(a,d){a?console.log(a):models.Course.findOne({studygroup:c.studygroup},
function(a,c){c&&b.emit("linkchanged",c)})})});b.on("getsessiondata",function(c){models.SessionData.find({userId:c,elapsedTime:{$gt:0}},function(c,a){""!=a&&b.emit("sessionfound",a)})});b.on("getsessiondataonkey",function(a){models.SessionData.find({_id:a},function(a,c){null!=c&&b.emit("sessionkeyfound",c)})});b.on("destroysession",function(a){models.SessionData.remove({_id:a._id},function(a){a&&console.log(a)})});b.on("disconnect",function(){console.log("User disconnected");users--;b.emit("count",
{count:users});b.broadcast.emit("count",{count:users});b.broadcast.emit("user:left",{name:a});userNames.free(a);var c=d.indexOf(b.username);d.splice(c,1);b.emit("updateUserList",{user:b.username,connectionType:"delete"})})});
