var express=require("express"),http=require("http"),fs=require("fs"),path=require("path"),mongoose=require("mongoose"),io=require("socket.io"),ObjId=require("mongodb").ObjectID,mongoURI=process.env.MONGOLAB_URI||"mongodb://mtc9831:2ndmay12@ds151048.mlab.com:51048/lumina",options={server:{poolSize:5,socketOptions:{keepAlive:1}}},db=mongoose.connect(mongoURI,options),Schema=mongoose.Schema,ObjectID=Schema.ObjectId,EM=require("./app/server/modules/email-dispatcher"),routes=require("./auth_routes"),ExternalUserHandler=
require("./handlers/ExternalUserHandler"),AuthHandler=require("./handlers/AuthHandler"),passport=require("passport"),google_strategy=require("passport-google-oauth").OAuth2Strategy,windowslive_Strategy=require("passport-windowslive"),facebook_strategy=require("passport-facebook"),linkedIn_strategy=require("passport-linkedin").Strategy,YahooStrategy=require("passport-yahoo").Strategy,twitter_strategy=require("passport-twitter"),app=module.exports=express();app.mongoose=require("mongoose");
var models={};models.Registration=require("./models/registration.js")(app.mongoose).model;models.BlogPost=require("./models/blogpost.js")(app.mongoose).model;models.EssayTopic=require("./models/essayTopic.js")(app.mongoose).model;models.Feedback=require("./models/feedback.js")(app.mongoose).model;models.SessionData=require("./models/sessionData.js")(app.mongoose).model;models.LoginRecord=require("./models/loginRecord.js")(app.mongoose).model;models.ExternalUser=require("./models/ExternalUser.js")(app.mongoose).model;
app.configure(function(){app.set("views",__dirname+"/app/server/views");app.set("view engine","jade");process.env.NODE_TLS_REJECT_UNAUTHORIZED="0";app.locals.pretty=!0;app.use(express.favicon(__dirname+"/public/favicon.ico"));app.set("view options",{layout:!1});app.use(express.logger("dev"));app.use(express.json());app.use(express.urlencoded());app.use(express.cookieParser());app.use(express.session({secret:"super-duper-secret-secret"}));app.use(express.methodOverride());app.use(express.static(path.join(__dirname,
"public")));app.use(require("stylus").middleware({src:__dirname+"/app/public"}));app.use(express.static(__dirname+"/app/public"));app.use(passport.initialize());app.set("client-url","http://www.cliquelearn.org");app.set("client-google-signin","/google?action=signin");app.disable("x-powered-by");app.use(app.router)});
var allowCrossDomain=function(a,d,b){d.header("Access-Control-Allow-Origin","*");d.header("Access-Control-Allow-Methods","GET,PUT,POST,DELETE");d.header("Access-Control-Allow-Headers","Content-Type, Authorization");"OPTIONS"==a.method?d.send(200):b()};passport.serializeUser(function(a,d){d(null,a)});passport.deserializeUser(function(a,d){d(null,a)});
passport.use(new google_strategy({clientID:"135981056725-9h7pv94fq7l1b4tsh5hh5lor6i02qofl.apps.googleusercontent.com",clientSecret:"z7dCXbnbzXzM8n8Y-UcbJArH",callbackURL:"http://www.cliquelearn.org/auth/google/callback"},function(a,d,b,c){models.ExternalUser.update({email:b._json.emails[0].value},{last_name:"undefined"===typeof b._json.name.familyName?"":b._json.name.familyName,first_name:"undefined"===typeof b._json.name.givenName?"":b._json.name.givenName,email:"undefined"===typeof b._json.emails[0].value?
"":b._json.emails[0].value,token:a},{upsert:!0},function(a,d){a&&console.log(a);process.nextTick(function(){return c(null,b)})})}));
passport.use(new windowslive_Strategy({clientID:"0000000040178602",clientSecret:"xWCJqfZYPT76nQ7U0drWkP3LcMv6WEua",callbackURL:"http://www.cliquelearn.org/auth/windowslive/callback"},function(a,d,b,c){models.ExternalUser.update({email:b._json.emails.preferred},{last_name:"undefined"===typeof b._json.last_name?"":b._json.last_name,first_name:"undefined"===typeof b._json.first_name?"":b._json.first_name,email:"undefined"===typeof b._json.emails.preferred?"":b._json.emails.preferred,token:a},{upsert:!0},
function(a,d){a&&console.log(a);process.nextTick(function(){return c(null,b)})})}));
passport.use(new facebook_strategy({clientID:"101528843551743",clientSecret:"5acdd4bf1c9c4fa20d1fee7dd6062f88",callbackURL:"http://www.cliquelearn.org/auth/facebook/callback",enableProof:!1},function(a,d,b,c){models.ExternalUser.update({email:b._json.email},{last_name:"undefined"===typeof b._json.last_name?"":b._json.last_name,first_name:"undefined"===typeof b._json.first_name?"":b._json.first_name,email:"undefined"===typeof b._json.email?"":b._json.email,token:a},{upsert:!0},function(a,d){a&&console.log(a);
process.nextTick(function(){return c(null,b)})})}));passport.use(new linkedIn_strategy({consumerKey:"75o4ldp4squ3kh",consumerSecret:"SUNfIaKnQJe452BD",callbackURL:"http://www.cliquelearn.org/auth/linkedIn/callback"},function(a,d,b,c){process.nextTick(function(){return c(null,b)})}));
passport.use(new YahooStrategy({clientId:"dj0yJmk9azRhRXhnTUtZVW1ZJmQ9WVdrOU0xZHVlSHBQTldNbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD02Zg--",clientSecret:"ed9005f68736cf3ede6ca8c0f66b078b87ea9794",returnURL:"http://cliqueserv.org/auth/yahoo/return",realm:"http://cliqueserv.org/"},function(a,d,b){models.ExternalUser.update({email:d.emails[0].value},{last_name:"",first_name:"undefined"===typeof d.displayName?"":d.displayName,email:"undefined"===typeof d.emails[0].value?"":d.emails[0].value,token:a},{upsert:!0},
function(c,f){c&&console.log(c);process.nextTick(function(){d.identifier=a;return b(null,d)})})}));
passport.use(new twitter_strategy({consumerKey:"K0u1jqk9wB8XvhZLysyc0AjXJ",consumerSecret:"s1o3yHlytlpwfyCgwMAEvb14V5isH2TpCxRKjMfxCRwjZ7lORB",callbackURL:"http://www.cliquelearn.org/auth/twitter/callback"},function(a,d,b,c){models.ExternalUser.update({email:b.username+"@twitter.com"},{last_name:"",first_name:"undefined"===typeof b.displayName?"":b.displayName,email:"undefined"===typeof b.username?"":b.username+"@twitter.com",token:a},{upsert:!0},function(a,d){a&&console.log(a);process.nextTick(function(){return c(null,
b)})})}));var handlers={ExternalUser:new ExternalUserHandler,auth:new AuthHandler};routes.setup(app,handlers);require("./app/server/router")(app,models);
var server_port=process.env.OPENSHIFT_NODEJS_PORT||80,server_ip_address=process.env.OPENSHIFT_NODEJS_IP||"127.0.0.1",server=http.createServer(app).listen(server_port,server_ip_address,function(){console.log("Listening on "+server_ip_address+", port "+server_port)}),sio=io.listen(server),users=0,userNames=function(){var a={};return{claim:function(d){return!d||a[d]?!1:a[d]=!0},free:function(d){a[d]&&delete a[d]},get:function(){var d=[];for(user in a)d.push(user);return d}}}();
sio.sockets.on("connection",function(a){users++;a.emit("count",{count:users});a.broadcast.emit("count",{count:users});var d=[];a.emit("newUserList",{userList:d});a.on("addUser",function(c){var b=c.name,e=c.testname;"undefined"===typeof b?console.log("User logged off!"):(a.username=b,console.log(b+" has joined"),d.push(b),a.emit("updateUserList",{user:b,connectionType:"add"}),fs.stat(__dirname+"/lib/"+e+".json",function(c,b){c||fs.readFile(__dirname+"/lib/"+e+".json","Utf-8",function(c,b){c?console.log(c):
a.emit("sendQuestions",JSON.parse(b))})}))});a.on("destroysession",function(a){models.SessionData.remove({sessionId:a},function(a){a&&console.log(a)})});a.on("selectedTopic",function(c){c=fs.readFileSync(__dirname+"/app/server/views/courses/"+c.course+"/"+c.subsection+"/"+c.topic+".html","ascii");a.emit("topicfound",c)});var b="";a.on("init",function(c){b=c;userNames.claim(c);a.emit("init",{name:c,users:userNames.get()});a.broadcast.emit("user:join",{name:c})});a.on("loadextusers",function(){models.ExternalUser.find({},
function(c,b){c||a.emit("extusersfound",b)})});a.on("deleteextuser",function(a){models.ExternalUser.remove({email:a},function(a){a&&console.log(a)})});a.on("getessaytopic",function(c){models.EssayTopic.count({},function(c,b){if(!c){var d=1+Math.floor(Math.random()*b);models.EssayTopic.find({topicId:d},function(c,b){c?console.log(c):0==b.length?a.emit("topicnotfound","Error: Can't generate topics"):a.emit("topicfound",b[0].essayTopic)})}})});a.on("loadcourses",function(c){models.Course.findOne({studygroup:c.studygroup},
function(b,d){d&&(1==c.searchItem?a.emit("coursefound",d):2==c.searchItem?a.emit("referencefound",d):3==c.searchItem&&a.emit("linkfound",d))})});a.on("addcourse",function(c){models.Course.update({studyGroup:c.studyGroup},{$addToSet:{links:{courseCaption:c.courseCaption,courseHyperLink:c.courseHyperLink,courseType:c.courseType}}},{upsert:!0},function(b,d){b?console.log(b):models.Course.findOne({studygroup:c.studygroup},function(c,b){b&&a.emit("coursechanged",b)})})});a.on("addreference",function(b){models.Course.update({studyGroup:b.studyGroup},
{$addToSet:{referenceMaterials:{courseCaption:b.courseCaption,courseHyperLink:b.courseHyperLink,courseType:b.courseType}}},{upsert:!0},function(d,e){d?console.log(d):models.Course.findOne({studygroup:b.studygroup},function(b,c){c&&a.emit("referencechanged",c)})})});a.on("getsessiondata",function(b){models.SessionData.find({userId:b,elapsedTime:{$gt:0}},function(b,c){""!=c&&a.emit("sessionfound",c)})});a.on("getsessiondataonkey",function(b){models.SessionData.find({_id:b},function(b,c){null!=c&&a.emit("sessionkeyfound",
c)})});a.on("destroysession",function(a){models.SessionData.remove({_id:a._id},function(a){a&&console.log(a)})});a.on("disconnect",function(){console.log("User disconnected");users--;a.emit("count",{count:users});a.broadcast.emit("count",{count:users});a.broadcast.emit("user:left",{name:b});userNames.free(b);var c=d.indexOf(a.username);d.splice(c,1);a.emit("updateUserList",{user:a.username,connectionType:"delete"})})});
