var ExternalUserDB=require("../models/ExternalUser"),AuthHandler=function(){this.interest_choice="";this.googleSignIn=googleSignIn;this.googleSignInCallback=googleSignInCallback;this.facebookSignIn=facebookSignIn;this.facebookSignInCallback=facebookSignInCallback;this.windowsliveSignIn=windowsliveSignIn;this.windowsliveSignInCallback=windowsliveSignInCallback;this.linkedInSignIn=linkedInSignIn;this.linkedInSignInCallback=linkedInSignInCallback;this.yahooSignIn=yahooSignIn;this.yahooSignInCallback=
yahooSignInCallback;this.twitterSignIn=twitterSignIn;this.twitterSignInCallback=twitterSignInCallback;this.localSignIn=localSignIn;this.localSignInCallback=localSignInCallback};function googleSignIn(a,b,c){passport=a._passport.instance;this.interest_choice=a.param("interest");passport.authenticate("google",{scope:"https://www.googleapis.com/auth/userinfo.email"},function(a,b,c){})(a,b,c)}
function facebookSignIn(a,b,c){passport=a._passport.instance;this.interest_choice=a.param("interest");passport.authenticate("facebook",{scope:["public_profile","email"]},function(a,b,c){})(a,b,c)}function windowsliveSignIn(a,b,c){passport=a._passport.instance;this.interest_choice=a.param("interest");passport.authenticate("windowslive",{scope:["wl.emails","wl.basic"]},function(a,b,c){})(a,b,c)}
function linkedInSignIn(a,b,c){passport=a._passport.instance;this.interest_choice=a.param("interest");passport.authenticate("linkedin",{scope:["r_basicprofile","r_emailaddress"]},function(a,b,c){})(a,b,c)}function yahooSignIn(a,b,c){passport=a._passport.instance;this.interest_choice=a.param("interest");passport.authenticate("yahoo",{failureRedirect:"/oauth"},function(a,b,c){})(a,b,c)}
function twitterSignIn(a,b,c){passport=a._passport.instance;this.interest_choice=a.param("interest");passport.authenticate("twitter",{failureRedirect:"/oauth"},function(a,b,c){})(a,b,c)}
function googleSignInCallback(a,b,c){passport=a._passport.instance;passport.authenticate("google",function(d,e,f){if(d)return c(d);if(!e)return b.redirect("http://www.cliquelearn.org");d={user:"ExternalUser",email:e.emails[0].value,contactno:"",country:"",role:"ExternalUser",board:"",standard:"",isActive:!0,isLocked:!1};a.session.user=d;a.session.role=d.role;"undefined"===typeof this.interest_choice?b.writeHead(302,{Location:"http://www.cliquelearn.org/student"}):b.writeHead(302,{Location:"http://www.cliquelearn.org/openresources2?interest="+
this.interest_choice});b.end()})(a,b,c)}
function facebookSignInCallback(a,b,c){passport=a._passport.instance;passport.authenticate("facebook",function(d,e,f){if(d)return c(d);if(!e)return b.redirect("http://www.cliquelearn.org");d={user:"ExternalUser",email:e.emails[0].value,contactno:"",country:"",role:"ExternalUser",board:"",standard:"",isActive:!0,isLocked:!1};a.session.user=d;a.session.role=d.role;"undefined"===typeof this.interest_choice?b.writeHead(302,{Location:"http://www.cliquelearn.org/student"}):b.writeHead(302,{Location:"http://www.cliquelearn.org/openresources2?interest="+
this.interest_choice});b.end()})(a,b,c)}
function windowsliveSignInCallback(a,b,c){passport=a._passport.instance;passport.authenticate("windowslive",function(d,e,f){if(d)return c(d);if(!e)return b.redirect("http://www.cliquelearn.org");d={user:"ExternalUser",email:e.emails[0].value,contactno:"",country:"",role:"ExternalUser",board:"",standard:"",isActive:!0,isLocked:!1};a.session.user=d;a.session.role=d.role;"undefined"===typeof this.interest_choice?b.writeHead(302,{Location:"http://www.cliquelearn.org/student"}):(a.session.role="ExternalUser",
b.writeHead(302,{Location:"http://www.cliquelearn.org/openresources2?interest="+this.interest_choice}));b.end()})(a,b,c)}
function linkedInSignInCallback(a,b,c){passport=a._passport.instance;passport.authenticate("linkedin",function(d,e,f){if(d)return c(d);if(!e)return b.redirect("http://www.cliquelearn.org");d={user:"ExternalUser",email:e.emails[0].value,contactno:"",country:"",role:"ExternalUser",board:"",standard:"",isActive:!0,isLocked:!1};a.session.user=d;a.session.role=d.role;"undefined"===typeof this.interest_choice?b.writeHead(302,{Location:"http://www.cliquelearn.org/student"}):(a.session.role="ExternalUser",
b.writeHead(302,{Location:"http://www.cliquelearn.org/openresources2?interest="+this.interest_choice}));b.end()})(a,b,c)}
function yahooSignInCallback(a,b,c){passport=a._passport.instance;passport.authenticate("yahoo",function(d,e,f){if(d)return c(d);if(!e)return b.redirect("http://www.cliquelearn.org");d={user:"ExternalUser",email:e.emails[0].value,contactno:"",country:"",role:"ExternalUser",board:"",standard:"",isActive:!0,isLocked:!1};a.session.user=d;a.session.role=d.role;"undefined"===typeof this.interest_choice?b.writeHead(302,{Location:"http://www.cliquelearn.org/student"}):(a.session.role="ExternalUser",b.writeHead(302,
{Location:"http://www.cliquelearn.org/openresources2?interest="+this.interest_choice}));b.end()})(a,b,c)}
function twitterSignInCallback(a,b,c){passport=a._passport.instance;passport.authenticate("twitter",function(d,e,f){if(d)return c(d);if(!e)return b.redirect("http://www.cliquelearn.org");d={user:"ExternalUser",email:e.username+"@twitter.com",contactno:"",country:"",role:"ExternalUser",board:"",standard:"",isActive:!0,isLocked:!1};a.session.user=d;a.session.role=d.role;"undefined"===typeof this.interest_choice?b.writeHead(302,{Location:"http://www.cliquelearn.org/student"}):(a.session.role="ExternalUser",
b.writeHead(302,{Location:"http://www.cliquelearn.org/openresources2?interest="+this.interest_choice}));b.end()})(a,b,c)}function localSignIn(a,b,c){}function localSignInCallback(a,b,c){}module.exports=AuthHandler;
